# Generated by sector-rotation-trader/scripts/export_stockarithm_labs.py
from datetime import datetime, timedelta
from typing import Iterable

import pandas as pd


def fetch_rss_counts(feed_urls: Iterable, days_back: int = 7) -> pd.DataFrame:
    """
    Fetch RSS feeds and return counts per day.
    Columns: date, count.
    Returns empty DataFrame if feedparser is missing or on any failure.
    """
    try:
        import feedparser
    except ImportError:
        return pd.DataFrame()

    try:
        cutoff = datetime.utcnow().date() - timedelta(days=days_back)
        rows = []
        for url in feed_urls:
            feed = feedparser.parse(url)
            for entry in feed.entries:
                published = entry.get("published_parsed") or entry.get("updated_parsed")
                if not published:
                    continue
                day = datetime(*published[:6]).date()
                if day < cutoff:
                    continue
                rows.append({"date": day.isoformat(), "count": 1})
        df = pd.DataFrame(rows)
        if df.empty:
            return df
        df["date"] = pd.to_datetime(df["date"])
        df = df.groupby("date")["count"].sum().reset_index()
        return df.sort_values("date")
    except Exception:
        return pd.DataFrame()
