# Generated by sector-rotation-trader/scripts/export_stockarithm_labs.py
from stockarithm_labs.adapters import fetch_google_trends


if __name__ == "__main__":
    df = fetch_google_trends("urgent home repair", days_back=90)
    print(df.tail())
