# Generated by sector-rotation-trader/scripts/export_stockarithm_labs.py
from __future__ import annotations

import pandas as pd


def toy_signal(path: str = "samples/google_trends_urgent_home_repair.csv") -> str:
    df = pd.read_csv(path)
    if len(df) < 4:
        return "HOLD"
    latest = float(df["interest"].iloc[-1])
    trailing_mean = float(df["interest"].iloc[-4:-1].mean())
    return "WATCH" if latest > trailing_mean * 1.10 else "HOLD"


if __name__ == "__main__":
    print(toy_signal())
