# Generated by sector-rotation-trader/scripts/export_stockarithm_labs.py
from __future__ import annotations


ADAPTER_KEYWORDS = {
    "google_trends": ["google trends", "search interest", "search volume", "trends"],
    "rss_count": ["rss", "feed", "news feed", "news volume", "article count"],
    "fred_series": ["fred", "federal reserve", "economic data", "series id"],
    "eia_electricity": ["eia", "electricity", "power demand", "grid demand"],
    "openchargemap": ["openchargemap", "ev charger", "charging station", "ev station"],
    "tsa_table": ["tsa", "passenger", "throughput", "airport"],
    "weather_series": ["weather", "temperature", "precipitation", "heat", "cold"],
}

MIN_SCORE = 2


def score_text(text: str) -> dict[str, int]:
    text_l = text.lower()
    scores: dict[str, int] = {}
    for adapter, keywords in ADAPTER_KEYWORDS.items():
        score = 0
        for keyword in keywords:
            if keyword in text_l:
                score += 2 if " " in keyword else 1
        if score:
            scores[adapter] = score
    return scores


def route_text(text: str) -> list[str]:
    scores = score_text(text)
    if not scores:
        return []
    max_score = max(scores.values())
    if max_score < MIN_SCORE:
        return []
    return sorted(adapter for adapter, score in scores.items() if score == max_score)


if __name__ == "__main__":
    import json
    import sys

    text = " ".join(sys.argv[1:]) or sys.stdin.read()
    print(json.dumps({"adapters": route_text(text), "scores": score_text(text)}, indent=2))
