# Generated by sector-rotation-trader/scripts/export_stockarithm_labs.py
from __future__ import annotations

import json
import os
from datetime import datetime, timedelta
from pathlib import Path
from typing import Callable, TypeVar


DEFAULT_CACHE_DIR = os.getenv("STOCKARITHM_CACHE_DIR", ".cache/stockarithm-labs")
T = TypeVar("T")


def cached_fetch(cache_path: str | os.PathLike[str], ttl_hours: int, fetch_fn: Callable[[], T]) -> T:
    path = Path(cache_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    now = datetime.utcnow()
    if path.exists():
        try:
            payload = json.loads(path.read_text())
            fetched_at = payload.get("fetched_at")
            if fetched_at and now - datetime.fromisoformat(fetched_at) < timedelta(hours=ttl_hours):
                return payload.get("data")
        except Exception:
            pass
    data = fetch_fn()
    path.write_text(json.dumps({"fetched_at": now.isoformat(), "data": data}, indent=2, default=str))
    return data
